---
port: 4000
host: 0.0.0.0
safe: false

exclude: [README.md, .gitignore]
timezone: null
lsi: false
markdown: kramdown

### content configuration ###
title:       "Tutorial on Large Language Models for Tabular Data (LLM4Table)"
keywords:    "tutorial"
description: "The official website for the Tutorial on Large Language Models for Tabular Data"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"

collections:
  - pages_2022
